
const chapters=QUESTION_BANK.chapters.filter(c=>QUESTION_BANK.questions.some(q=>q.chapter===c.id));
const all=QUESTION_BANK.questions;let state={chapter:chapters[0].id,index:0,order:[],selected:null,mindChapter:chapters[0].title};
function shuffle(a){let b=[...a];for(let i=b.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b}
function esc(s){return String(s??'').replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]))}
function setChapter(id){state.chapter=id;state.order=shuffle(all.filter(q=>q.chapter===id));state.index=0;renderTabs();renderQuiz()}
function renderTabs(){let nav=document.getElementById('chapterTabs');nav.innerHTML='';chapters.forEach(c=>{let b=document.createElement('button');b.textContent=c.title.replace(/^第\s*(\d+)\s*章/,'第$1章 ');b.className=c.id===state.chapter?'active':'';b.onclick=()=>{showQuiz();setChapter(c.id)};nav.appendChild(b)})}
function current(){return state.order[state.index]}
function isCorrect(label,ans){return String(ans||'').replace(/\s/g,'').includes(label)}
function renderQuiz(){let q=current();document.getElementById('chapterName').textContent=q.chapterTitle;document.getElementById('progress').textContent=(state.index+1)+' / '+state.order.length;document.getElementById('typeName').textContent=q.type+' · 原题第'+q.number+'题';document.getElementById('stem').textContent=q.stem;let ops=document.getElementById('options');ops.innerHTML='';(q.options||[]).forEach(o=>{let b=document.createElement('button');b.className='option';b.textContent=o.label+'．'+o.text;b.onclick=()=>{state.selected=o.label;showExplain()};ops.appendChild(b)});document.getElementById('explain').classList.add('hidden');state.selected=null}
function showExplain(){let q=current();document.querySelectorAll('.option').forEach(btn=>{let label=btn.textContent.split('．')[0];btn.classList.toggle('selected',label===state.selected);btn.classList.toggle('correct',isCorrect(label,q.answer));btn.classList.toggle('wrong',label===state.selected&&!isCorrect(label,q.answer))});let optionHtml='';if(q.options&&q.options.length){optionHtml='<h3>选项解析：为什么对 / 为什么错</h3>'+q.options.map(o=>{let good=isCorrect(o.label,q.answer);let text=(q.optionAnalysis&&q.optionAnalysis[o.label])?q.optionAnalysis[o.label]:(good?'正确。':'错误。');return '<div class="why '+(good?'good':'bad')+'"><b>'+esc(o.label)+'项</b>：'+esc(text)+'</div>'}).join('')}let termHtml='<h3>知识点和名词解释</h3>'+(q.termDefinitions?Object.entries(q.termDefinitions).map(([k,v])=>'<div class="why"><b>'+esc(k)+'</b>：'+esc(v)+'</div>').join(''):'');let main='<h3>答案</h3><span class="answer-pill">'+esc(q.answer||'见解析')+'</span><h3>详细解题路线</h3><div class="why">'+esc(q.explanation||'').replace(/\n/g,'<br>')+'</div>';let box=document.getElementById('explain');box.innerHTML=main+optionHtml+termHtml;box.classList.remove('hidden')}
function showQuiz(){document.getElementById('quiz').classList.remove('hidden');document.getElementById('mindmap').classList.add('hidden')}
function showMind(){document.getElementById('quiz').classList.add('hidden');document.getElementById('mindmap').classList.remove('hidden');renderMind()}
function renderMind(){let filter=document.getElementById('termSearch').value.trim();let sections=QUESTION_BANK.mindmap||[];let tree='<div class="root-node">金融学总复习思维导图：名词—关系—考法</div>';sections.forEach(sec=>{let cnt=sec.items.filter(it=>!filter||it.term.includes(filter)||it.desc.includes(filter)||sec.chapter.includes(filter)).length;if(filter&&!cnt)return;let active=sec.chapter===state.mindChapter?'active':'';tree+='<div class="tree-chapter '+active+'" data-ch="'+esc(sec.chapter)+'"><b>'+esc(sec.chapter)+'</b><span>'+cnt+' 个核心名词</span></div>'});document.getElementById('mindTree').innerHTML=tree;document.querySelectorAll('.tree-chapter').forEach(el=>el.onclick=()=>{state.mindChapter=el.dataset.ch;renderMind()});let sec=sections.find(s=>s.chapter===state.mindChapter)||sections[0];let items=sec.items.filter(it=>!filter||it.term.includes(filter)||it.desc.includes(filter)||sec.chapter.includes(filter));if(filter){items=[];sections.forEach(s=>s.items.forEach(it=>{if(it.term.includes(filter)||it.desc.includes(filter)||s.chapter.includes(filter))items.push({...it,chapter:s.chapter})}))}let detail='<div class="detail-card"><h3>'+(filter?'搜索结果':'当前章节：'+esc(sec.chapter))+'</h3><p>每个节点都来自题库中反复考到的名词。先记“名词是什么意思”，再去做题会容易很多。</p></div><div class="term-grid">';items.forEach(it=>{detail+='<div class="term-node"><b>'+esc(it.term)+'</b><p>'+esc(it.desc)+'</p><span class="tag">'+esc(it.chapter||sec.chapter)+'</span></div>'});detail+='</div>';document.getElementById('mindDetail').innerHTML=detail}
document.getElementById('showAnswer').onclick=showExplain;document.getElementById('nextBtn').onclick=()=>{state.index=(state.index+1)%state.order.length;renderQuiz()};document.getElementById('prevBtn').onclick=()=>{state.index=(state.index-1+state.order.length)%state.order.length;renderQuiz()};document.getElementById('mapBtn').onclick=showMind;document.getElementById('quizBtn').onclick=showQuiz;document.getElementById('termSearch').oninput=renderMind;setChapter(chapters[0].id);renderMind();
